on:
  push:
    branches:
      - "main"

env:
  CI: ""

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create .env
      run: |
        echo "VITE_API_ID=${{ secrets.VITE_API_ID }}" > .env
        echo "VITE_API_HASH=${{ secrets.VITE_API_HASH }}" >> .env

    - id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        path: build
      env:
        VITE_API_ID: ${{ secrets.VITE_API_ID }}
        VITE_API_HASH: ${{ secrets.VITE_API_HASH }}
